apiVersion: v1
kind: Pod
metadata:
  name: podmountsvolume-diamonddelt
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvolclaim-diamonddelt
  containers:
  - image: ubuntu:latest
    name: ubuntu-container
    command:
    - /bin/bash
    - "-c"
    - "sleep 90m"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /data
      name: data