apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol-diamonddelt
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ssd
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: main-disk